[libraries]
android-application-comAndroidApplicationGradlePlugin = { module = "com.android.application:com.android.application.gradle.plugin", version = "7.4.1" }
android-library-comAndroidLibraryGradlePlugin = { module = "com.android.library:com.android.library.gradle.plugin", version = "7.4.1" }
android-tools-desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version = "2.0.2" }
android-toolsBuild-gradle = { module = "com.android.tools.build:gradle", version = "7.4.1" }
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version = "1.6.1" }
androidx-activity-activityKtx = { module = "androidx.activity:activity-ktx", version = "1.6.1" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-compose-animation-animation = { module = "androidx.compose.animation:animation", version = "1.3.3" }
androidx-compose-animation-animationCore = { module = "androidx.compose.animation:animation-core", version = "1.3.3" }
androidx-compose-animation-animationGraphics = { module = "androidx.compose.animation:animation-graphics", version = "1.3.3" }
androidx-compose-compiler-compiler = { module = "androidx.compose.compiler:compiler", version = "1.4.2" }
androidx-compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version = "1.3.1" }
androidx-compose-foundation-foundationLayout = { module = "androidx.compose.foundation:foundation-layout", version = "1.3.1" }
androidx-compose-foundation-foundationText = { module = "androidx.compose.foundation:foundation-text", version = "1.2.1" }
androidx-compose-material-material = { module = "androidx.compose.material:material", version = "1.3.1" }
androidx-compose-material-materialIconsCore = { module = "androidx.compose.material:material-icons-core", version = "1.3.1" }
androidx-compose-material-materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version = "1.3.1" }
androidx-compose-material-materialRipple = { module = "androidx.compose.material:material-ripple", version = "1.3.1" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3", version = "1.0.1" }
androidx-compose-material3-material3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version = "1.0.1" }
androidx-compose-runtime-runtime = { module = "androidx.compose.runtime:runtime", version = "1.3.3" }
androidx-compose-runtime-runtimeSaveable = { module = "androidx.compose.runtime:runtime-saveable", version = "1.3.3" }
androidx-compose-runtime-runtimeTracing = { module = "androidx.compose.runtime:runtime-tracing", version = "1.0.0-alpha02" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version = "1.3.3" }
androidx-compose-ui-uiTest = { module = "androidx.compose.ui:ui-test", version = "1.3.3" }
androidx-compose-ui-uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version = "1.3.3" }
androidx-compose-ui-uiTooling = { module = "androidx.compose.ui:ui-tooling", version = "1.3.3" }
androidx-compose-ui-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version = "1.3.3" }
androidx-compose-ui-uiUtil = { module = "androidx.compose.ui:ui-util", version = "1.3.3" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-core-coreSplashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }
androidx-hilt-hiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }
androidx-lifecycle-viewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.5.1" }
androidx-navigation-navigationCompose = { module = "androidx.navigation:navigation-compose", version = "2.5.3" }
arrowKt-arrowCore = { module = "io.arrow-kt:arrow-core", version = "1.1.5" }
cash-turbine-turbine = { module = "app.cash.turbine:turbine", version = "0.12.1" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version = "0.43" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version = "1.0.0-alpha.29" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version = "1.0.0-alpha.29" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version = "0.1.0-alpha.12" }
javiersc-kotlin-kotlinTestJunit = { module = "com.javiersc.kotlin:kotlin-test-junit", version = "0.1.0-alpha.12" }
javiersc-kotlin-kotlinTestJunit5 = { module = "com.javiersc.kotlin:kotlin-test-junit5", version = "0.1.0-alpha.12" }
javiersc-kotlin-kotlinTestNG = { module = "com.javiersc.kotlin:kotlin-test-testng", version = "0.1.0-alpha.12" }
javiersc-kotlinx-coroutinesRunBlocking = { module = "com.javiersc.kotlinx:coroutines-run-blocking", version = "0.1.0-rc.1" }
javiersc-kotlinx-coroutinesRunBlockingAll = { module = "com.javiersc.kotlinx:coroutines-run-blocking-all", version = "0.1.0-rc.1" }
javiersc-mokoki-mokoki = { module = "com.javiersc.mokoki:mokoki", version = "0.2.0-alpha.1" }
javiersc-mokoki-mokokiSerialization = { module = "com.javiersc.mokoki:mokoki-serialization", version = "0.2.0-alpha.1" }
javiersc-network-networkEither = { module = "com.javiersc.network:network-either", version = "0.2.0-alpha.1" }
javiersc-network-networkEitherLogger = { module = "com.javiersc.network:network-either-logger", version = "0.2.0-alpha.1" }
javiersc-network-networkResourceEitherExtensions = { module = "com.javiersc.network:network-resource-either-extensions", version = "0.2.0-alpha.1" }
javiersc-network-resourceEither = { module = "com.javiersc.network:resource-either", version = "0.2.0-alpha.1" }
javiersc-semver-core = { module = "com.javiersc.semver:semver-core", version = "0.1.0-beta.13" }
jetbrains-kotlin-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version = "1.8.10" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version = "1.8.10" }
jetbrains-kotlin-kotlinTestAnnotationsCommon = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version = "1.8.10" }
jetbrains-kotlin-kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version = "1.8.10" }
jetbrains-kotlin-kotlinTestJUnit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version = "1.8.10" }
jetbrains-kotlin-kotlinTestNG = { module = "org.jetbrains.kotlin:kotlin-test-testng", version = "1.8.10" }
jetbrains-kotlinx-kotlinxCollectionsImmutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.5" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.6.4" }
jetbrains-kotlinx-kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
jetbrains-kotlinx-kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.4.1" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.1" }
junit-jupiter-junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.9.2" }
junit-jupiter-junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.9.2" }
kotest-extensions-kotestAssertionsArrow = { module = "io.kotest.extensions:kotest-assertions-arrow", version = "1.3.0" }
kotest-extensions-kotestExtensionsAllure = { module = "io.kotest.extensions:kotest-extensions-allure", version = "1.2.0" }
kotest-extensions-kotestAssertionsCompiler = { module = "io.kotest.extensions:kotest-assertions-compiler", version = "1.0.0" }
kotest-extensions-kotestExtensionsEmbeddedKafka = { module = "io.kotest.extensions:kotest-extensions-embedded-kafka", version = "1.0.6" }
kotest-extensions-kotestAssertionsJsoup = { module = "io.kotest.extensions:kotest-assertions-jsoup", version = "1.0.0" }
kotest-extensions-kotestAssertionsKlock = { module = "io.kotest.extensions:kotest-assertions-klock", version = "1.0.0" }
kotest-extensions-kotestExtensionsKoin = { module = "io.kotest.extensions:kotest-extensions-koin", version = "1.1.0" }
kotest-extensions-kotestAssertionsKonform = { module = "io.kotest.extensions:kotest-assertions-konform ", version = "1.0.1" }
kotest-extensions-kotestAssertionsKotlinxDatetime = { module = "io.kotest.extensions:kotest-assertions-kotlinx-datetime ", version = "1.0.1" }
kotest-extensions-kotestAssertionsKtor = { module = "io.kotest.extensions:kotest-assertions-ktor", version = "1.0.3" }
kotest-extensions-kotestExtensionsMockserver = { module = "io.kotest.extensions:kotest-extensions-mockserver", version = "1.2.1" }
kotest-extensions-kotestExtensionsRobolectric = { module = "io.kotest.extensions:kotest-extensions-robolectric", version = "0.5.0" }
kotest-extensions-kotestExtensionsSpring = { module = "io.kotest.extensions:kotest-extensions-spring", version = "1.1.2" }
kotest-extensions-kotestExtensionsTestcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version = "1.3.4" }
kotest-extensions-kotestExtensionsWiremock = { module = "io.kotest.extensions:kotest-extensions-wiremock", version = "1.0.3" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version = "5.5.4" }
kotest-kotestAssertionsJson = { module = "io.kotest:kotest-assertions-json", version = "5.5.4" }
kotest-kotestAssertionsSql = { module = "io.kotest:kotest-assertions-sql", version = "5.5.4" }
kotest-kotestProperty = { module = "io.kotest:kotest-property", version = "5.5.4" }
kotest-kotestRunnerJUnit4 = { module = "io.kotest:kotest-runner-junit4", version = "5.5.4" }
kotest-kotestRunnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version = "5.5.4" }
ktor-ktorClientCio = { module = "io.ktor:ktor-client-cio", version = "2.2.3" }
ktor-ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "2.2.3" }
ktor-ktorClientCore = { module = "io.ktor:ktor-client-core", version = "2.2.3" }
ktor-ktorClientMock = { module = "io.ktor:ktor-client-mock", version = "2.2.3" }
ktor-ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version = "2.2.3" }
ktor-ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "2.2.3" }
russhwolf-multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version = "1.0.0" }
russhwolf-multiplatformSettingsCoroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version = "1.0.0" }
russhwolf-multiplatformSettingsDatastore = { module = "com.russhwolf:multiplatform-settings-datastore", version = "1.0.0" }
russhwolf-multiplatformSettingsNoArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version = "1.0.0" }
russhwolf-multiplatformSettingsSerialization = { module = "com.russhwolf:multiplatform-settings-serialization", version = "1.0.0" }
russhwolf-multiplatformSettingsTest = { module = "com.russhwolf:multiplatform-settings-test", version = "1.0.0" }
squareup-moshi-moshi = { module = "com.squareup.moshi:moshi", version = "1.14.0" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "5.0.0-alpha.11" }
squareup-okhttp3-mockwebserver3Junit4 = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version = "5.0.0-alpha.11" }
squareup-okhttp3-mockwebserver3Junit5 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version = "5.0.0-alpha.11" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.11" }
squareup-okio-okio = { module = "com.squareup.okio:okio", version = "3.3.0" }
squareup-retrofit2-converterKotlinxSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "0.8.0" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.9.0" }
squareup-retrofit2-retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version = "2.9.0" }
