[versions]
androidxActivityCompose = "1.5.0"
androidxActivityKtx = "1.5.0"
androidxAppCompat = "1.4.2"
androidxCore = "1.8.0"
arrow = "1.1.2"
coroutines = "1.6.4"
datetime = "0.4.0"
javierscGradleExtensions = "1.0.0-alpha.26"
javierscKotlinStdlib = "0.1.0-alpha.11"
kotest = "5.3.2"
kotlin = "1.6.21"
ktfmt = "0.39"
ktor = "2.0.4"
mokoki = "0.1.0-alpha.9"
moshi = "1.13.0"
okHttp = "4.10.0"
okio = "3.2.0"
retrofit = "2.9.0"
retrofitConverterKotlinxSerialization = "0.8.0"
runBlocking = "0.1.0-rc.1"
serialization = "1.3.3"
turbine = "0.8.0"

[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }
androidx-activity-activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivityKtx" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
arrowKt-arrowCore = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
cash-turbine-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version.ref = "javierscGradleExtensions" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version.ref = "javierscGradleExtensions" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
javiersc-kotlin-kotlinTestJunit = { module = "com.javiersc.kotlin:kotlin-test-junit", version.ref = "javierscKotlinStdlib" }
javiersc-kotlin-kotlinTestJunit5 = { module = "com.javiersc.kotlin:kotlin-test-junit5", version.ref = "javierscKotlinStdlib" }
javiersc-kotlin-kotlinTestNG = { module = "com.javiersc.kotlin:kotlin-test-testng", version.ref = "javierscKotlinStdlib" }
javiersc-kotlinx-coroutinesRunBlocking = { module = "com.javiersc.kotlinx:coroutines-run-blocking", version.ref = "runBlocking" }
javiersc-kotlinx-coroutinesRunBlockingAll = { module = "com.javiersc.kotlinx:coroutines-run-blocking-all", version.ref = "runBlocking" }
javiersc-mokoki-mokokiCore = { module = "com.javiersc.mokoki:mokoki-core", version.ref = "mokoki" }
javiersc-mokoki-mokokiSerialization = { module = "com.javiersc.mokoki:mokoki-serialization", version.ref = "mokoki" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jetbrains-kotlin-kotlinTestAnnotationsCommon = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
jetbrains-kotlin-kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
jetbrains-kotlin-kotlinTestJUnit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
jetbrains-kotlin-kotlinTestNG = { module = "org.jetbrains.kotlin:kotlin-test-testng", version.ref = "kotlin" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
jetbrains-kotlinx-kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
ktor-ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-ktorClientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ktorClientMock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
squareup-moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okHttp" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
squareup-okio-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit2-converterKotlinxSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitConverterKotlinxSerialization" }
