[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version = "1.5.1" }
androidx-activity-activityKtx = { module = "androidx.activity:activity-ktx", version = "1.5.1" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version = "1.9.0" }
arrowKt-arrowCore = { module = "io.arrow-kt:arrow-core", version = "1.1.2" }
cash-turbine-turbine = { module = "app.cash.turbine:turbine", version = "0.9.0" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version = "0.39" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version = "1.0.0-alpha.26" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version = "1.0.0-alpha.26" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestJunit = { module = "com.javiersc.kotlin:kotlin-test-junit", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestJunit5 = { module = "com.javiersc.kotlin:kotlin-test-junit5", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestNG = { module = "com.javiersc.kotlin:kotlin-test-testng", version = "0.1.0-alpha.11" }
javiersc-kotlinx-coroutinesRunBlocking = { module = "com.javiersc.kotlinx:coroutines-run-blocking", version = "0.1.0-rc.1" }
javiersc-kotlinx-coroutinesRunBlockingAll = { module = "com.javiersc.kotlinx:coroutines-run-blocking-all", version = "0.1.0-rc.1" }
javiersc-mokoki-mokoki = { module = "com.javiersc.mokoki:mokoki", version = "0.2.0-alpha.1" }
javiersc-mokoki-mokokiSerialization = { module = "com.javiersc.mokoki:mokoki-serialization", version = "0.2.0-alpha.1" }
javiersc-network-networkEither = { module = "com.javiersc.network:network-either", version = "0.2.0-alpha.1" }
javiersc-network-networkEitherLogger = { module = "com.javiersc.network:network-either-logger", version = "0.2.0-alpha.1" }
javiersc-network-networkResourceEitherExtensions = { module = "com.javiersc.network:network-resource-either-extensions", version = "0.2.0-alpha.1" }
javiersc-network-resourceEither = { module = "com.javiersc.network:resource-either", version = "0.2.0-alpha.1" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version = "1.7.10" }
jetbrains-kotlin-kotlinTestAnnotationsCommon = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version = "1.7.10" }
jetbrains-kotlin-kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version = "1.7.10" }
jetbrains-kotlin-kotlinTestJUnit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version = "1.7.10" }
jetbrains-kotlin-kotlinTestNG = { module = "org.jetbrains.kotlin:kotlin-test-testng", version = "1.7.10" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.6.4" }
jetbrains-kotlinx-kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
jetbrains-kotlinx-kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.4.0" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.0" }
junit-jupiter-junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version = "5.9.0" }
junit-jupiter-junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version = "5.9.0" }
kotest-extensions-kotestExtensionsAllure = { module = "io.kotest.extensions:kotest-extensions-allure", version = "1.2.0" }
kotest-extensions-kotestExtensionsEmbeddedKafka = { module = "io.kotest.extensions:kotest-extensions-embedded-kafka", version = "1.0.6" }
kotest-extensions-kotestExtensionsKoin = { module = "io.kotest.extensions:kotest-extensions-koin", version = "1.1.0" }
kotest-extensions-kotestExtensionsMockserver = { module = "io.kotest.extensions:kotest-extensions-mockserver", version = "1.2.1" }
kotest-extensions-kotestExtensionsRobolectric = { module = "io.kotest.extensions:kotest-extensions-robolectric", version = "0.5.0" }
kotest-extensions-kotestExtensionsSpring = { module = "io.kotest.extensions:kotest-extensions-spring", version = "1.1.2" }
kotest-extensions-kotestExtensionsTestcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version = "1.3.4" }
kotest-extensions-kotestExtensionsWiremock = { module = "io.kotest.extensions:kotest-extensions-wiremock", version = "1.0.3" }
kotest-kotestAssertionsArrow = { module = "io.kotest:kotest-assertions-arrow", version = "5.4.0" }
kotest-kotestAssertionsCompiler = { module = "io.kotest:kotest-assertions-compiler", version = "5.4.0" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version = "5.4.2" }
kotest-kotestAssertionsJson = { module = "io.kotest:kotest-assertions-json", version = "5.4.2" }
kotest-kotestAssertionsJsoup = { module = "io.kotest:kotest-assertions-jsoup", version = "5.4.0" }
kotest-kotestAssertionsKlock = { module = "io.kotest:kotest-assertions-klock", version = "5.4.0" }
kotest-kotestAssertionsKonform  = { module = "io.kotest:kotest-assertions-konform ", version = "5.4.0" }
kotest-kotestAssertionsKotlinxDateTime  = { module = "io.kotest:kotest-assertions-kotlinx-time ", version = "5.4.0" }
kotest-kotestAssertionsKtor  = { module = "io.kotest:kotest-assertions-ktor", version = "5.4.0" }
kotest-kotestAssertionsSql  = { module = "io.kotest:kotest-assertions-sql", version = "5.4.2" }
kotest-kotestCore = { module = "io.kotest:kotest-core", version = "5.4.0" }
kotest-kotestProperty = { module = "io.kotest:kotest-property", version = "5.4.2" }
kotest-kotestPropertyArrow = { module = "io.kotest:kotest-property-arrow", version = "5.4.0" }
kotest-kotestRunnerJUnit4 = { module = "io.kotest:kotest-runner-junit4", version = "5.4.2" }
kotest-kotestRunnerJUnit5 = { module = "io.kotest:kotest-runner-junit5", version = "5.4.2" }
ktor-ktorClientCio = { module = "io.ktor:ktor-client-cio", version = "2.1.1" }
ktor-ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "2.1.1" }
ktor-ktorClientCore = { module = "io.ktor:ktor-client-core", version = "2.1.1" }
ktor-ktorClientMock = { module = "io.ktor:ktor-client-mock", version = "2.1.1" }
ktor-ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version = "2.1.1" }
ktor-ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "2.1.1" }
squareup-moshi-moshi = { module = "com.squareup.moshi:moshi", version = "1.14.0" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "5.0.0-alpha.10" }
squareup-okhttp3-mockwebserver3Junit4 = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version = "5.0.0-alpha.10" }
squareup-okhttp3-mockwebserver3Junit5 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version = "5.0.0-alpha.10" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.10" }
squareup-okio-okio = { module = "com.squareup.okio:okio", version = "3.2.0" }
squareup-retrofit2-converterKotlinxSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "0.8.0" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.9.0" }
squareup-retrofit2-retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version = "2.9.0" }
