[libraries]
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version = "1.5.0" }
androidx-activity-activityKtx = { module = "androidx.activity:activity-ktx", version = "1.5.0" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
androidx-core-coreKtx = { module = "androidx.core:core-ktx", version = "1.8.0" }
arrowKt-arrowCore = { module = "io.arrow-kt:arrow-core", version = "1.1.2" }
cash-turbine-turbine = { module = "app.cash.turbine:turbine", version = "0.8.0" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version = "0.39" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version = "1.0.0-alpha.26" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version = "1.0.0-alpha.26" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestJunit = { module = "com.javiersc.kotlin:kotlin-test-junit", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestJunit5 = { module = "com.javiersc.kotlin:kotlin-test-junit5", version = "0.1.0-alpha.11" }
javiersc-kotlin-kotlinTestNG = { module = "com.javiersc.kotlin:kotlin-test-testng", version = "0.1.0-alpha.11" }
javiersc-kotlinx-coroutinesRunBlocking = { module = "com.javiersc.kotlinx:coroutines-run-blocking", version = "0.1.0-rc.1" }
javiersc-kotlinx-coroutinesRunBlockingAll = { module = "com.javiersc.kotlinx:coroutines-run-blocking-all", version = "0.1.0-rc.1" }
javiersc-mokoki-mokoki = { module = "com.javiersc.mokoki:mokoki", version = "0.2.0-alpha.1" }
javiersc-mokoki-mokokiSerialization = { module = "com.javiersc.mokoki:mokoki-serialization", version = "0.2.0-alpha.1" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version = "1.6.21" }
jetbrains-kotlin-kotlinTestAnnotationsCommon = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version = "1.6.21" }
jetbrains-kotlin-kotlinTestJUnit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version = "1.6.21" }
jetbrains-kotlin-kotlinTestJUnit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version = "1.6.21" }
jetbrains-kotlin-kotlinTestNG = { module = "org.jetbrains.kotlin:kotlin-test-testng", version = "1.6.21" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version = "1.6.4" }
jetbrains-kotlinx-kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.4.0" }
jetbrains-kotlinx-kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.3.3" }
jetbrains-kotlinx-kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.3.3" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version = "5.4.0" }
kotest-kotestProperty = { module = "io.kotest:kotest-property", version = "5.4.0" }
ktor-ktorClientCio = { module = "io.ktor:ktor-client-cio", version = "2.0.3" }
ktor-ktorClientContentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version = "2.0.3" }
ktor-ktorClientCore = { module = "io.ktor:ktor-client-core", version = "2.0.3" }
ktor-ktorClientMock = { module = "io.ktor:ktor-client-mock", version = "2.0.3" }
ktor-ktorClientOkHttp = { module = "io.ktor:ktor-client-okhttp", version = "2.0.3" }
ktor-ktorSerializationKotlinxJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version = "2.0.3" }
squareup-moshi-moshi = { module = "com.squareup.moshi:moshi", version = "1.13.0" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version = "5.0.0-alpha.10" }
squareup-okhttp3-mockwebserver3Junit4 = { module = "com.squareup.okhttp3:mockwebserver3-junit4", version = "5.0.0-alpha.10" }
squareup-okhttp3-mockwebserver3Junit5 = { module = "com.squareup.okhttp3:mockwebserver3-junit5", version = "5.0.0-alpha.10" }
squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.0.0-alpha.10" }
squareup-okio-okio = { module = "com.squareup.okio:okio", version = "3.2.0" }
squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.9.0" }
squareup-retrofit2-retrofitMock = { module = "com.squareup.retrofit2:retrofit-mock", version = "2.9.0" }
squareup-retrofit2-converterKotlinxSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "0.8.0" }
