[versions]
coroutines = "1.6.3"
javierscGradleExtensions = "1.0.0-alpha.22"
javierscKotlinStdlib = "0.1.0-alpha.5"
ktfmt = "0.39"

[libraries]
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version.ref = "javierscGradleExtensions" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version.ref = "javierscGradleExtensions" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
