[versions]
activity = "1.5.0"
coroutines = "1.6.3"
javierscGradleExtensions = "1.0.0-alpha.26"
javierscKotlinStdlib = "0.1.0-alpha.7"
kotest = "5.3.2"
kotlin = "1.6.21"
ktfmt = "0.39"

[libraries]
androidx-activity-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
javiersc-gradle-gradleExtensions = { module = "com.javiersc.gradle:gradle-extensions", version.ref = "javierscGradleExtensions" }
javiersc-gradle-gradleTestExtensions = { module = "com.javiersc.gradle:gradle-test-extensions", version.ref = "javierscGradleExtensions" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jetbrains-kotlinx-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotest-kotestAssertionsCore = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }

[bundles]
androidLibrary = [
    "androidx-activity-activityKtx",
    "javiersc-kotlin-kotlinStdlib",
    "jetbrains-kotlinx-kotlinxCoroutinesAndroid",
    "jetbrains-kotlinx-kotlinxCoroutinesCore",
    "jetbrains-kotlinx-kotlinxCoroutinesTest",
    "jetbrains-kotlin-kotlinTest",
    "kotest-kotestAssertionsCore",
]
gradlePlugin = [
    "javiersc-gradle-gradleExtensions",
    "javiersc-gradle-gradleTestExtensions",
    "javiersc-kotlin-kotlinStdlib",
    "jetbrains-kotlin-kotlinTest",
    "kotest-kotestAssertionsCore",
]
jvm = [
    "javiersc-gradle-gradleExtensions",
    "javiersc-gradle-gradleTestExtensions",
    "javiersc-kotlin-kotlinStdlib",
    "jetbrains-kotlinx-kotlinxCoroutinesAndroid",
    "jetbrains-kotlinx-kotlinxCoroutinesCore",
    "jetbrains-kotlinx-kotlinxCoroutinesTest",
    "jetbrains-kotlin-kotlinTest",
    "kotest-kotestAssertionsCore",
]
multiplatform = [
    "javiersc-kotlin-kotlinStdlib",
    "jetbrains-kotlinx-kotlinxCoroutinesAndroid",
    "jetbrains-kotlinx-kotlinxCoroutinesCore",
    "jetbrains-kotlinx-kotlinxCoroutinesTest",
    "jetbrains-kotlin-kotlinTest",
    "kotest-kotestAssertionsCore",
]
