[versions]
coroutines = "1.5.2"
gson = "2.8.9"
javierscKotlinStdlib = "0.1.0-alpha.1"
jgit = "5.13.0.202109080827-r"
jsoup = "1.14.3"
kotest = "4.6.3"
ktfmt = "0.30"
semanticVersioning = "0.1.0-beta.6"
tomlj = "1.0.0"

[libraries]
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
google-codeGson-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
javiersc-semanticVersioning-semanticVersioningCore = { module = "com.javiersc.semantic-versioning:semantic-versioning-core", version.ref = "semanticVersioning" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jsoup-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
