[versions]
coroutines = "1.6.1"
gson = "2.9.0"
javierscKotlinStdlib = "0.1.0-alpha.4"
jgit = "6.1.0.202203080745-r"
jsoup = "1.14.3"
kotest = "5.3.0"
ktfmt = "0.35"
semver = "0.1.0-beta.10"
tomlj = "1.0.0"

[libraries]
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
google-codeGson-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javiersc-kotlin-kotlinStdlib = { module = "com.javiersc.kotlin:kotlin-stdlib", version.ref = "javierscKotlinStdlib" }
javiersc-semver-semverCore = { module = "com.javiersc.semver:semver-core", version.ref = "semver" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jsoup-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
