[versions]
coroutines = "1.5.2"
gson = "2.8.8"
jgit = "5.13.0.202109080827-r"
jsoup = "1.14.3"
kotest = "4.6.3"
ktfmt = "0.29"
semanticVersioning = "0.1.0-alpha.4"

[libraries]
eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
facebook-ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
google-codeGson-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
javiersc-semanticVersioning-semanticVersioningCore = { module = "com.javiersc.semantic-versioning:semantic-versioning-core", version.ref = "semanticVersioning" }
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlin-kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
jetbrains-kotlinx-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jsoup-jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

[bundles]
testing = ["jetbrains-kotlin-kotlinTest", "kotest-kotestAssertionsCore"]
