site_name: Hubdle
site_description: Single entry point to configurate any kind of project
site_author: Javier Segovia Córdoba
remote_branch: gh-pages

repo_name: Hubdle
repo_url: https://github.com/JavierSegoviaCordoba/hubdle

copyright: 'Copyright &copy; 2021 Javier Segovia Córdoba'

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon.png'
  logo: 'assets/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'

nav:
  - Overview: index.md
  - Extension overview: extensions/EXTENSION_OVERVIEW.md
  - Extensions:
    - config:
      - analysis: extensions/config/ANALYSIS.md
      - binary-compatibility-validator: extensions/config/BINARY_COMPATIBILITY_VALIDATOR.md
      - coverage: extensions/config/COVERAGE.md
      - documentation:
        - changelog: extensions/config/documentation/CHANGELOG.md
        - readme: extensions/config/documentation/README.md
        - site: extensions/config/documentation/SITE.md
      - explicit-api: extensions/config/EXPLICIT_API.md
      - format: extensions/config/FORMAT.md
      - install:
        - pre-commit: extensions/config/install/PRE_COMMIT.md
      - nexus: extensions/config/NEXUS.md
      - publishing: extensions/config/PUBLISHING.md
      - versioning: extensions/config/VERSIONING.md
    - kotlin:
        - android:
          - library: extensions/kotlin/android/LIBRARY.md
        - gradle:
            - plugin: extensions/kotlin/gradle/PLUGIN.md
            - version-catalog: extensions/kotlin/gradle/VERSION_CATALOG.md
        - jvm: extensions/kotlin/JVM.md
        - multiplatform: extensions/kotlin/MULTIPLATFORM.md

plugins:
  - search

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JavierSegoviaCordoba
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JavierSegoviaCo

extra_css:
  - css/all.css
