site_name: Hubdle
site_description: Single entry point to configurate any kind of project
site_author: Javier Segovia Córdoba
remote_branch: gh-pages

repo_name: Hubdle
repo_url: https://github.com/JavierSegoviaCordoba/hubdle

copyright: 'Copyright &copy; 2021 Javier Segovia Córdoba'

theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon.png'
  logo: 'assets/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Fira Sans'
    code: 'JetBrains Mono'

nav:
  - Overview: index.md
  - Extension overview: extensions/HUBDLE_EXTENSION/
  - Extensions:
    - config:
      - analysis: extensions/config/ANALYSIS/
      - binary-compatibility-validator: extensions/config/BINARY_COMPATIBILITY_VALIDATOR/
      - coverage: extensions/config/COVERAGE/
      - documentation: extensions/config/DOCUMENTATION/
      - explicit-api: extensions/config/EXPLICIT_API/
      - format: extensions/config/format/FORMAT/
      - install: extensions/config/install/INSTALL/
      - language-settings: extensions/config/language-settings/LANGUAGE_SETTINGS/
      - nexus: extensions/config/NEXUS/
      - publishing: extensions/config/PUBLISHING/
      - versioning: extensions/config/VERSIONING/
    - kotlin:
        - android: extensions/kotlin/ANDROID/
        - jvm: extensions/kotlin/JVM/
        - multiplatform: extensions/kotlin/MULTIPLATFORM/

plugins:
  - search

markdown_extensions:
  - admonition
  - smarty
  - codehilite:
      guess_lang: false
      linenums: True
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JavierSegoviaCordoba
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JavierSegoviaCo

extra_css:
  - css/all.css
