name: apply-format

on:
  workflow_dispatch:

jobs:
  apply-format:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/apply-format.yaml@main
    with:
      restore-kotlin-native-cache: false
    secrets: inherit
