name: build-kotlin-tag-p

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-plugin:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@main
    with:
      allow-github-actor-bots: false
      gradle-args-publish-snapshot: '-P semver.tagPrefix=p'
      run_before_args: './gradlew assemble publishToMavenLocalTest'
      restore-kotlin-native-cache: false
    secrets: inherit
