name: build-kotlin-dispatcher

on:
  workflow_dispatch:
    inputs:
      gradle-args:
        description: 'Gradle args for every step'
        default: ''
        required: false
      publish-all-docs:
        description: 'Publish all docs instead of only API docs and reports'
        required: false
        default: false
        type: boolean
      machines:
        default: "[ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]"
        description: 'Operative systems to run the build step'
        required: false
        type: string

jobs:
  build:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@main
    with:
      allow-github-actor-bots: false
      gradle-args: '${{ github.event.inputs.gradle-args }}'
      publish-all-docs: '${{ github.event.inputs.publish-all-docs }}'
      machines: '${{ github.event.inputs.machines }}'
    secrets: inherit
