name: build-kotlin-jvm

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

  workflow_dispatch:
    inputs:
      args:
        description: 'Gradle args for `build` step'
        default: ''
        required: false

jobs:
  build:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin-jvm.yaml@main
    with:
      args: '${{ github.event.inputs.args }}'
    secrets:
      OSS_USER: '${{ secrets.OSS_USER }}'
      OSS_TOKEN: '${{ secrets.OSS_TOKEN }}'
      OSS_STAGING_PROFILE_ID: '${{ secrets.OSS_STAGING_PROFILE_ID }}'
