name: build-kotlin-tag-c

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build-version-catalog:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-kotlin.yaml@main
    with:
      allow-github-actor-bots: false
      code-quality-check: false
      deploy-docs: false
      gradle-args-publish-snapshot: '-P semver.tagPrefix=c'
      run_before_args: './gradlew assemble publishToMavenLocalTest'
      restore-kotlin-native-cache: false
    secrets: inherit
