name: build-changelog-renovate-bot

on:
  push:
    branches:
      - 'renovate/**'

jobs:
  add-updated-dependencies-to-changelog:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/build-changelog-renovate-bot.yaml@main
    with:
      auto-approve: false
      gradle-args: '-Phubdle.catalog.renovate=true'
      restore-kotlin-native-cache: false
      tag-prefix: 'c'
    secrets: inherit
