name: build-itself

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-itself:
    if: (!contains(github.actor, '[bot]'))

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Restore Kotlin native cache
        uses: actions/cache@v3.0.10
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-konan-

      - name: Set up Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.2
        with:
          gradle-home-cache-cleanup: true

      - name: Set Hubdle version output
        id: semver
        run: ./gradlew printSemver -Psemver.stage=snapshot --githubOnlyRoot --githubOutput

      - name: Publish next version to MavenLocal
        run: ./gradlew publishToMavenLocal -Psemver.stage=snapshot

      - name: Check format
        continue-on-error: true
        run: |
          hubdleVersion=${{ steps.semver.outputs.semver }}
          ./gradlew checkFormat -PhubdleVersion=$hubdleVersion -Psemver.stage=beta

      - name: Build
        run: |
          hubdleVersion=${{ steps.semver.outputs.semver }}
          ./gradlew build -PhubdleVersion=$hubdleVersion -Psemver.stage=beta -x checkFormat -x spotlessCheck -x spotlessKotlinCheck
