name: generate-version-tag

on:
  workflow_dispatch:
    if: github.ref == 'refs/heads/main'
    inputs:
      publish-project:
        description: 'Project to publish'
        required: true
        default: 'plugin'
        type: choice
        options:
          - 'plugin'
          - 'catalog'
      stage:
        description: 'Stage'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
          - 'auto'
      scope:
        description: 'Scope'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'auto'

jobs:
  plugin:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    if: "${{ github.event.inputs.publish-project == 'plugin' }}"
    with:
      project-path: ':'
      stage: '${{ github.event.inputs.stage }}'
      scope: '${{ github.event.inputs.scope }}'
      restore-kotlin-native-cache: false
    secrets: inherit

  catalog:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    if: "${{ github.event.inputs.publish-project == 'catalog' }}"
    with:
      semver-output-field: 'SEMVER_HUBDLE_VERSION_CATALOG'
      project-path: 'hubdle-version-catalog:'
      tag-prefix: 'c'
      stage: '${{ github.event.inputs.stage }}'
      scope: '${{ github.event.inputs.scope }}'
      restore-kotlin-native-cache: false
    secrets: inherit
