name: generate-version-tag

on:
  workflow_dispatch:
    inputs:
      publish_project:
        description: 'Project to publish'
        required: true
        default: 'plugin'
        type: choice
        options:
          - 'plugin'
          - 'catalog'
          - 'declarative'
      stage:
        description: 'Stage'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
          - 'auto'
      scope:
        description: 'Scope'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'
          - 'auto'

jobs:
  generate-version-tag-template: &generate-version-tag
    if: github.ref == 'refs/heads/main'
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    with:
      stage: '${{ github.event.inputs.stage }}'
      scope: '${{ github.event.inputs.scope }}'
      restore-kotlin-native-cache: false
    secrets: inherit

  plugin:
    if: (github.event.inputs.publish_project == 'plugin') && (github.ref == 'refs/heads/main')
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    with:
      project-path: ':'
      restore-kotlin-native-cache: false
      scope: '${{ github.event.inputs.scope }}'
      stage: '${{ github.event.inputs.stage }}'
      tag-prefix: 'p'
    secrets: inherit

  catalog:
    if: (github.event.inputs.publish_project == 'catalog') && (github.ref == 'refs/heads/main')
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    with:
      project-path: 'hubdle-version-catalog:'
      restore-kotlin-native-cache: false
      scope: '${{ github.event.inputs.scope }}'
      semver-output-field: 'SEMVER_HUBDLE_VERSION_CATALOG'
      stage: '${{ github.event.inputs.stage }}'
      tag-prefix: 'c'
    secrets: inherit

  declarative:
    if: (github.event.inputs.publish_project == 'declarative') && (github.ref == 'refs/heads/main')
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/generate-version-tag.yaml@main
    with:
      project-path: 'hubdle-declarative-gradle:'
      restore-kotlin-native-cache: false
      scope: '${{ github.event.inputs.scope }}'
      semver-output-field: 'SEMVER_HUBDLE_DECLARATIVE_GRADLE'
      stage: '${{ github.event.inputs.stage }}'
      tag-prefix: 'd'
    secrets: inherit
