name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@hubdle
    with:
      code-coverage-report: true
      publish-gradle-plugin-portal: true
      gradle-args-build: '--exclude-task spotlessCheck'
    secrets: inherit
