name: publish-kotlin

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@main
    with:
      publish-gradle-plugin-portal: true
      gradle-args-build: '--exclude-task spotlessCheck'
      changelog-file-c-tag-prefix: 'hubdle-gradle-plugin/CHANGELOG.md'
    secrets: inherit
