name: publish-kotlin

on:
  push:
    tags:
      - '!c**'

jobs:
  publish:
    uses: JavierSegoviaCordoba/reusable-workflows/.github/workflows/publish-kotlin.yaml@main
    with:
      publish-gradle-plugin-portal: true
      gradle-args-build: '--exclude-task spotlessCheck'
      gradle-args-publish-maven-central: '-P publishing.sign=true'
      restore-kotlin-native-cache: false
    secrets: inherit
